In [1]:
#In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.
#More specifically we're going to cover:
# *Introduction
# *Getting information from tensors
# *Manipulating tensors
# *Tensors & NumPy
# *Using @tf.function (a way to speed up my regular Python functions)
# Exercises to do for my self!!!!

In [2]:
## Introduction to Tensors
import tensorflow as tf
print(tf.__version__)

2.10.0


In [3]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check number of dimensions of a tensor (ndim stands for number of dimenstions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
# Create a matrix 
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
matrix_2 = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
matrix_2.ndim

2

In [11]:
# Create a tensor
tensor = tf.constant([[ [1, 2, 3],
                       [2, 4, 5],
                       [2, 3, 3]
                       ]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 4, 5],
        [2, 3, 3]]])>

In [12]:
tensor.ndim

3

In [13]:
tensor_2 = tf.constant([[1, 3, 2],
                          [2, 3, 3],
                          [1, 2, 3]])
tensor_2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 3, 2],
       [2, 3, 3],
       [1, 2, 3]])>

In [14]:
# Creating tensors with with ft.variable(changable tensor)
changable_t = tf.Variable([10, 7])
unchangable_t = tf.Variable([10, 7])
changable_t, unchangable_t

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>)

In [15]:
changable_t[0].assign(12)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([12,  7])>

In [16]:
# Create random tensors
tensor_3 = tf.Variable([[[1, 2, 3],
                         [2, 4, 6],
                         [2, 2, 3],
                         [2, 2, 4]]])
tensor_3

<tf.Variable 'Variable:0' shape=(1, 4, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 4, 6],
        [2, 2, 3],
        [2, 2, 4]]])>

In [17]:
# Create random tensors
rand_1 = tf.random.Generator.from_seed(42)
rand_1 = rand_1.normal(shape=(3, 2))
rand_1
rand_2 = tf.random.Generator.from_seed(42)
rand_2 = rand_2.uniform(shape=(3, 2))
rand_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [18]:
rand_3 = tf.random.Generator.from_seed(42)
rand_3 = rand_3.normal(shape=(3, 2))
rand_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
rand_1, rand_3, rand_1 == rand_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [20]:
#Shaffle the order of the elements 
not_shuffled = tf.constant([[7, 10],
                            [1, 3],
                            [2, 2]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 1,  3],
       [ 2,  2]])>

In [21]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  2],
       [ 1,  3],
       [ 7, 10]])>

In [22]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 1,  3],
       [ 2,  2]])>

In [23]:
# Other ways to create tensors

In [24]:
tf.ones(shape=(4, 4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.ones([4, 4])*3

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>

tf.zeros(shape=(4,4))

In [26]:
tf.zeros(shape=(4,4))+2

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)>

In [27]:
tf.eye(4,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [28]:
#Turn NumPy array to Tensors
#Tensors can run much faster on a GPU for numerical computing
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
numpy_tf = tf.constant(numpy_A, shape=(2, 3, 4))
numpy_tf

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [30]:
#Get information from tensors
# Shape
# Rank
# Axis or dimension
# Size
tf.shape(numpy_tf), numpy_tf.ndim, tf.size(numpy_tf)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>,
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [31]:
tf.shape(scalar)

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [32]:
scalar.ndim

0

In [33]:
tensor_4 = tf.constant([[1, 2, 4],[1, 3, 5],[2, 4, 5]])

In [34]:
tensor_4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [1, 3, 5],
       [2, 4, 5]])>

In [35]:
tensor_4 = tf.constant([[[1, 2, 4],[1, 3, 5],[2, 4, 5]],
                         [[1, 2, 4],[3, 3, 3],[7, 8, 5]]])

In [36]:
tensor_4

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [1, 3, 5],
        [2, 4, 5]],

       [[1, 2, 4],
        [3, 3, 3],
        [7, 8, 5]]])>

In [37]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [39]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [40]:
rank_4_tensor = tf.ones(shape=(3,3,2,3))
rank_4_tensor

<tf.Tensor: shape=(3, 3, 2, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [41]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [42]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [43]:
rank_4_tensor[2]

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [44]:
rank_4_tensor.ndim

4

In [45]:
rank_4_tensor_rand = tf.random.Generator.from_seed(44)
rank_4_tensor_rand = rank_4_tensor_rand.normal(shape=(2,2,3,3))
rank_4_tensor_rand

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float32, numpy=
array([[[[-0.7535805 , -0.57166284,  0.1480774 ],
         [-0.23362993, -0.3522796 ,  0.40621263],
         [-1.0523509 ,  1.2054597 ,  1.6874489 ]],

        [[-0.4462975 , -2.3410842 ,  0.99009085],
         [-0.0876323 , -0.635568  , -0.6161736 ],
         [-1.9441465 , -0.48293006, -0.52447474]]],


       [[[-1.0345329 ,  1.3066901 , -1.5184573 ],
         [-0.4585211 ,  0.5714663 , -1.5331722 ],
         [ 0.45331386,  1.1487608 , -1.2659091 ]],

        [[-0.47450137,  2.006022  ,  0.28288034],
         [-0.30288252, -1.443651  ,  1.0034493 ],
         [ 0.20857747,  0.35700995,  1.0648885 ]]]], dtype=float32)>

In [46]:
# Get various attributes of our tensor
print("Data type of every element:",rank_4_tensor_rand.dtype)
print("Number of dimensions (rank):", rank_4_tensor_rand.ndim)
print("Shape of tensor: ", rank_4_tensor_rand.shape)
print("Elements along the 0 axis:",rank_4_tensor_rand.shape[0])
print("Elements along the last axis:", rank_4_tensor_rand.shape[-1])
print("Total number of elements in the tensor:",tf.size(rank_4_tensor_rand).numpy())

Data type of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor:  (2, 2, 3, 3)
Elements along the 0 axis: 2
Elements along the last axis: 3
Total number of elements in the tensor: 36


In [47]:
rank_4_tensor_rand[0][0][0][0],rank_4_tensor_rand[0][0][0][1],rank_4_tensor_rand[0][0][0][2]

(<tf.Tensor: shape=(), dtype=float32, numpy=-0.7535805>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.57166284>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.1480774>)

In [48]:
rank_4_tensor_rand[0][0][1][0],rank_4_tensor_rand[0][0][1][1],rank_4_tensor_rand[0][0][1][2]

(<tf.Tensor: shape=(), dtype=float32, numpy=-0.23362993>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.3522796>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.40621263>)

In [49]:
rank_4_tensor_rand[0][0][2][0],rank_4_tensor_rand[0][0][2][1],rank_4_tensor_rand[0][0][2][2]

(<tf.Tensor: shape=(), dtype=float32, numpy=-1.0523509>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.2054597>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.6874489>)

In [50]:
rank_4_tensor_rand[0][1][0][0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.4462975>

In [51]:
some_list = [[1, 2, 3, 4],[2, 3, 3]]
some_list[:2]

[[1, 2, 3, 4], [2, 3, 3]]

In [52]:
rank_4_tensor_rand[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[-0.7535805 , -0.57166284],
         [-0.23362993, -0.3522796 ]],

        [[-0.4462975 , -2.3410842 ],
         [-0.0876323 , -0.635568  ]]],


       [[[-1.0345329 ,  1.3066901 ],
         [-0.4585211 ,  0.5714663 ]],

        [[-0.47450137,  2.006022  ],
         [-0.30288252, -1.443651  ]]]], dtype=float32)>

In [53]:
# This way of indexing it becomes the shape of my tensor
rank_4_tensor_rand[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[-0.7535805 , -0.57166284,  0.1480774 ]]]], dtype=float32)>

In [54]:
rank_4_tensor_rand[:1, :1, :, :].ndim

4

In [55]:
rank_2_tensor = tf.random.Generator.from_seed(50)
rank_2_tensor = rank_2_tensor.normal(shape=(2,2))
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.45331386,  1.1487608 ],
       [-1.2659091 , -0.47450137]], dtype=float32)>

In [56]:
rank_2_tensor.ndim

2

In [57]:
rank_2_tensor[1][1].numpy()

-0.47450137

In [58]:
A = tf.constant([[1, 10],[2, 3]])
B = tf.constant([[12, 34],[33, 56]])
rank_2_ts = A + B
rank_2_ts

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 44],
       [35, 59]])>

In [59]:
rank_2_ts.shape, rank_2_ts.ndim

(TensorShape([2, 2]), 2)

In [60]:
#Get the last item of our tensor
rank_2_ts[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([44, 59])>

In [61]:
#Add in extra dimenstion to our rank 2 tensor
rank_3_ts = rank_2_ts[..., tf.newaxis]
rank_3_ts
rank_3_ts_new = rank_2_ts[..., ]
rank_3_ts_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 44],
       [35, 59]])>

In [62]:
#Aternative to tf.newaxis
tf.expand_dims(rank_2_ts, axis=-1, name="Rank_3_exp")

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[13],
        [44]],

       [[35],
        [59]]])>

In [63]:
rank_3_ts

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[13],
        [44]],

       [[35],
        [59]]])>

In [64]:
rank_3_ts_new
#tf.squeeze(rank_3_ts_new, axis=1)
#rank_3_ts_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 44],
       [35, 59]])>

In [65]:
# Manipulate tensors(tensor operations)
A, B

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 1, 10],
        [ 2,  3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12, 34],
        [33, 56]])>)

In [66]:
(A + B).numpy()

array([[13, 44],
       [35, 59]])

In [67]:
(A-B).numpy()

array([[-11, -24],
       [-31, -53]])

In [68]:
(A /B).numpy()

array([[0.08333333, 0.29411765],
       [0.06060606, 0.05357143]])

In [69]:
(A*B).numpy()

array([[ 12, 340],
       [ 66, 168]])

In [70]:
tf.math.multiply(A,B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 12, 340],
       [ 66, 168]])>

In [71]:
tf.math.acos(A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[          0, -2147483648],
       [-2147483648, -2147483648]])>

In [72]:
#Matrix multiplication in tensor
tf.linalg.matmul(A, B)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[342, 594],
       [123, 236]])>

In [73]:
A @ B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[342, 594],
       [123, 236]])>

In [74]:
#Create a tensor 3x3 and 3x2
C1 = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
C2 = tf.constant([[2, 4],[6, 8],[2, 3]])
C1, C2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [6, 8],
        [2, 3]])>)

In [75]:
C1@C2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 20,  29],
       [ 50,  74],
       [ 80, 119]])>

In [76]:
A1 = tf.constant([[2, 5, 6]])
A2 = tf.constant([[3],[4],[-5]])
A1@A2

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-4]])>

In [77]:
tf.linalg.matmul(A1,A2)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[-4]])>

In [78]:
A2@A1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  6,  15,  18],
       [  8,  20,  24],
       [-10, -25, -30]])>

In [79]:
B1 = tf.Variable([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.]])
B2 = tf.random.Generator.from_seed(60)
B2 = B2.uniform(shape=(3,3))
B1,B2

(<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.33705008, 0.7391062 , 0.16512096],
        [0.41555858, 0.78638244, 0.45899415],
        [0.42686343, 0.5630441 , 0.04115057]], dtype=float32)>)

In [80]:
tf.linalg.matmul(B1,B2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.4487576,  4.0010033,  1.206561 ],
       [ 5.987174 , 10.266602 ,  3.202358 ],
       [ 9.52559  , 16.5322   ,  5.198155 ]], dtype=float32)>

In [81]:
tf.matmul(B1,B2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.4487576,  4.0010033,  1.206561 ],
       [ 5.987174 , 10.266602 ,  3.202358 ],
       [ 9.52559  , 16.5322   ,  5.198155 ]], dtype=float32)>

In [82]:
tf.math.maximum(B1,B1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [83]:
C1 = tf.constant([[2, 4],[3, 4],[4, 5]])
C2 = tf.constant([[1, 3],[1, 5],[2, 8]])
C1,C2,tf.transpose(C2),C1@tf.transpose(C2)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 4],
        [4, 5]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [1, 5],
        [2, 8]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 2],
        [3, 5, 8]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[14, 22, 36],
        [15, 23, 38],
        [19, 29, 48]])>)

In [84]:
C1.shape[1]

2

In [85]:
C1@tf.reshape(C2, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 14, 34],
       [23, 17, 35],
       [29, 22, 44]])>

In [86]:
tf.tensordot(C1,tf.reshape(C2, shape=(2, 3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 14, 34],
       [23, 17, 35],
       [29, 22, 44]])>

In [87]:
tf.matmul(C1,tf.transpose(C1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[20, 22, 28],
       [22, 25, 32],
       [28, 32, 41]])>

In [88]:
print("Normal C1:")
print(C1.numpy())
print("Reshaped (2x3):")
print(tf.reshape(C1, shape=(2, 3)).numpy())
print("Transpose of C1:")
print(tf.transpose(C1).numpy())

Normal C1:
[[2 4]
 [3 4]
 [4 5]]
Reshaped (2x3):
[[2 4 3]
 [4 4 5]]
Transpose of C1:
[[2 3 4]
 [4 4 5]]


In [89]:
#Change data type of the tensor
C1,B1

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 4],
        [4, 5]])>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>)

In [90]:
C1,B1

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 4],
        [4, 5]])>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>)

In [91]:
# Casting
C_n = tf.cast(C1, dtype=tf.float16)
C_n

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 4.],
       [3., 4.],
       [4., 5.]], dtype=float16)>

In [92]:
#Aggregating tensors
B2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.33705008, 0.7391062 , 0.16512096],
       [0.41555858, 0.78638244, 0.45899415],
       [0.42686343, 0.5630441 , 0.04115057]], dtype=float32)>

In [93]:
tf.abs(B2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.33705008, 0.7391062 , 0.16512096],
       [0.41555858, 0.78638244, 0.45899415],
       [0.42686343, 0.5630441 , 0.04115057]], dtype=float32)>

In [94]:
tf.reduce_sum(B2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.9332705>

In [95]:
tf.reduce_max(B2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.78638244>

In [96]:
tf.math.reduce_std(tf.cast(C1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.9428091>

In [97]:
tf.math.reduce_variance(B2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.052319393>

In [98]:
tf.reduce_max(C1)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [99]:
B1,B2

(<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.33705008, 0.7391062 , 0.16512096],
        [0.41555858, 0.78638244, 0.45899415],
        [0.42686343, 0.5630441 , 0.04115057]], dtype=float32)>)

In [100]:
tf.tensordot(B1,B2,axes=2)

<tf.Tensor: shape=(), dtype=float32, numpy=18.52149>

In [101]:
tf.tensordot(B1,B2, axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.4487576,  4.0010033,  1.206561 ],
       [ 5.987174 , 10.266602 ,  3.202358 ],
       [ 9.52559  , 16.5322   ,  5.198155 ]], dtype=float32)>

In [102]:
tf.matmul(B1,B2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.4487576,  4.0010033,  1.206561 ],
       [ 5.987174 , 10.266602 ,  3.202358 ],
       [ 9.52559  , 16.5322   ,  5.198155 ]], dtype=float32)>

In [103]:
B1@B2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.4487576,  4.0010033,  1.206561 ],
       [ 5.987174 , 10.266602 ,  3.202358 ],
       [ 9.52559  , 16.5322   ,  5.198155 ]], dtype=float32)>

In [104]:
tf.matmul(B1,tf.reshape(B1, shape=(3,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]], dtype=float32)>

In [105]:
tf.matmul(B2,tf.transpose(B2))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.68714565, 0.7970737 , 0.5668185 ],
       [0.7970737 , 1.0017619 , 0.6390426 ],
       [0.5668185 , 0.6390426 , 0.5009244 ]], dtype=float32)>

In [106]:
B2,B1

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.33705008, 0.7391062 , 0.16512096],
        [0.41555858, 0.78638244, 0.45899415],
        [0.42686343, 0.5630441 , 0.04115057]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>)

In [107]:
tf.__version__

'2.10.0'

In [108]:
BC = tf.cast(B1, dtype=tf.int32)

In [109]:
Bc = tf.cast(B2, dtype=tf.int16)
Bc

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)>

In [110]:
B = tf.cast(B1, dtype=tf.int32)
tf.eye(4,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [111]:
tf.reduce_mean(C_n).numpy()

3.666

In [112]:
tf.math.reduce_std(C_n).numpy()

0.943

In [113]:
lstNum = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
tf.math.reduce_sum(lstNum)
lstNum = tf.cast(lstNum, dtype=tf.float16)
tf.math.reduce_variance(lstNum)
tf.math.reduce_std(lstNum)
tf.math.reduce_prod(lstNum)

<tf.Tensor: shape=(), dtype=float16, numpy=0.0>

In [114]:
C1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 4],
       [3, 4],
       [4, 5]])>

In [115]:
B1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [116]:
B2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.33705008, 0.7391062 , 0.16512096],
       [0.41555858, 0.78638244, 0.45899415],
       [0.42686343, 0.5630441 , 0.04115057]], dtype=float32)>

In [117]:
b = tf.random.uniform(shape=(10,5))
b.shape, b


(TensorShape([10, 5]),
 <tf.Tensor: shape=(10, 5), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
        [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
        [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
        [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
        [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
        [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
        [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ],
        [0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
        [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943],
        [0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
       dtype=float32)>)

In [118]:
assert b[1][tf.argmax(b[1][:])] == tf.reduce_max(b[1][:])

In [119]:
b = tf.reshape(b, shape=[1, 1, 1, 1, 50])
b_squeezed = tf.squeeze(b)
b,b_squeezed

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        

lstNum

In [120]:
lstNum,

(<tf.Tensor: shape=(10,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9., 0.], dtype=float16)>,)

In [121]:
lst = [3, 2, 1, 0]
tf.one_hot(lst, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)>

In [122]:
lstNum = tf.cast(lstNum, dtype=tf.int32)
tf.one_hot(lstNum, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [123]:
tf.ones_like(lstNum)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>

In [124]:
tf.one_hot(lstNum, depth=10, on_value="Yoo, I love depth learning", off_value="I also live programming")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'I also live programming', b'Yoo, I love depth learning',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also live programming'],
       [b'I also live programming', b'I also live programming',
        b'Yoo, I love depth learning', b'I also live programming',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also live programming'],
       [b'I also live programming', b'I also live programming',
        b'I also live programming', b'Yoo, I love depth learning',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also live programming',
        b'I also live programming', b'I also

In [125]:
indices = [1, 4, 6, 7, 3]
depth = 5
tf.one_hot(indices, depth=depth, on_value="Tee", off_value="King")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'King', b'Tee', b'King', b'King', b'King'],
       [b'King', b'King', b'King', b'King', b'Tee'],
       [b'King', b'King', b'King', b'King', b'King'],
       [b'King', b'King', b'King', b'King', b'King'],
       [b'King', b'King', b'King', b'Tee', b'King']], dtype=object)>

In [126]:
##Create tensor using range
H = tf.range(1, 5)
H

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [127]:
tf.math.sqrt(B2), tf.math.square(B2)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.58056015, 0.85971284, 0.4063508 ],
        [0.64463836, 0.88678205, 0.67749107],
        [0.65334785, 0.75036263, 0.20285603]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0.11360276, 0.54627794, 0.02726493],
        [0.17268893, 0.61839736, 0.21067563],
        [0.18221238, 0.31701863, 0.00169337]], dtype=float32)>)

In [128]:
tf.math.log(B2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.0875237 , -0.3023137 , -1.801077  ],
       [-0.8781317 , -0.24031204, -0.7787178 ],
       [-0.8512911 , -0.5743974 , -3.1905174 ]], dtype=float32)>

In [129]:
tf.sqrt(tf.math.log(B2))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=float32)>

In [130]:
tf.complex(2.,-2.).numpy()*tf.complex(3.,-2.).numpy()

(2-10j)

In [131]:
#NumPy and Tensor
J = tf.constant(np.array([1., 2., 3., 4.]))
J

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [132]:
np.array(J), np.array(J).dtype, type(np.array(J))

(array([1., 2., 3., 4.]), dtype('float64'), numpy.ndarray)

In [133]:
#Convert tensor J to NumPy
J.numpy()

array([1., 2., 3., 4.])

In [134]:
arr = np.array([1., 3, 4])
arr

array([1., 3., 4.])

In [135]:
arr.dtype

dtype('float64')

In [136]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

# Generate test data
test_x = tf.range(1, 10, 0.1)
test_y = (test_x * tf.math.log(test_x)) ** 3 / 2
test_y = tf.reshape(test_y, shape=(test_y.shape[0], 1))

# Convert Tensorflow tensors to numpy arrays
test_x_np = test_x.numpy()
test_y_np = test_y.numpy()

# Create a model
model_test = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu", input_shape=(1,)),  # Input shape needs to be specified for single-dimensional input
    tf.keras.layers.Dense(1)
])

# Compile the model
model_test.compile(loss="mae",
                   optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
                   metrics=["mae"])

# Fit the model
model_test.fit(test_x, test_y, epochs=10)

Epoch 1/10
3/3 [==============================] - 2s 11ms/step - loss: 1207.0557 - mae: 1207.0557
Epoch 2/10
3/3 [==============================] - 0s 19ms/step - loss: 1169.6895 - mae: 1169.6895
Epoch 3/10
3/3 [==============================] - 0s 14ms/step - loss: 1113.7583 - mae: 1113.7583
Epoch 4/10
3/3 [==============================] - 0s 7ms/step - loss: 1045.3481 - mae: 1045.3481
Epoch 5/10
3/3 [==============================] - 0s 8ms/step - loss: 986.1634 - mae: 986.1634
Epoch 6/10
3/3 [==============================] - 0s 6ms/step - loss: 930.9632 - mae: 930.9632
Epoch 7/10
3/3 [==============================] - 0s 7ms/step - loss: 897.8503 - mae: 897.8503
Epoch 8/10
3/3 [==============================] - 0s 18ms/step - loss: 885.0991 - mae: 885.0991
Epoch 9/10
3/3 [==============================] - 0s 6ms/step - loss: 877.5956 - mae: 877.5956
Epoch 10/10
3/3 [==============================] - 0s 11ms/step - loss: 873.2407 - mae: 873.2407


In [137]:
#Split the data into test set and train set
x_train = test_x[:72]
y_train = test_y[:72]

x_test = test_x[72:]
y_test = test_y[72:]

len(x_train), len(y_train), len(x_test), len(x_test)

(72, 72, 18, 18)

In [ ]:
plt.figure(figsize=(10, 7))
plt.scatter(x_train, y_train, c="b", label="Training data")
plt.scatter(x_test, y_test, c="g", label="Testing data")
plt.legend();