In [1]:
#Introduction to regression with neural networks in tensorflow
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
#Create data to view and fit
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

#Create features
x = np.array([-7., -4., -1., 2., 5., 8., 11., 14.])

#Create labels
y = np.array([3., 6., 9., 12., 15., 18., 21., 24.])
#plt.scatter(x,y)
#plt.xlabel('Features')
#plt.ylabel('Outputs')
#plt.title('x vs y')

In [3]:
y == x + 10

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [4]:
#Create a demo tensor for our housing prediction problem
#house_info = tf.constant(["bedroom", "bathroom", "garage"])
#house_price = tf.constant([939700])
#house_info, house_price

In [5]:
#input_shape = x.shape
#output_shape = y.shape
#input_shape, output_shape

In [6]:
x.shape, y.shape

((8,), (8,))

In [7]:
x[0].shape, y[0].shape

((), ())

In [8]:
X = tf.constant(x)
Y =tf.constant(y)
X.shape,Y.shape


(TensorShape([8]), TensorShape([8]))

In [9]:
#plt.plot(X,Y)

In [10]:
#Set random seed
tf.random.set_seed(42)

#Create a model using the Sequential API
# Reshape the input data to have two dimensions
X = tf.constant(x[:, np.newaxis])  # Reshaping x to a 2D array
Y = tf.constant(y)

# Rest of your code remains the same
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])
model.compile(loss=tf.keras.losses.mean_absolute_error,  # mean absolute error
              optimizer=tf.keras.optimizers.SGD(),  # stochastic gradient descent
              metrics=["mae"])

# Fit the model
model.fit(X, Y, epochs=5)


Epoch 1/5
1/1 [==============================] - 1s 1s/step - loss: 12.7756 - mae: 12.7756
Epoch 2/5
1/1 [==============================] - 0s 11ms/step - loss: 12.6431 - mae: 12.6431
Epoch 3/5
1/1 [==============================] - 0s 10ms/step - loss: 12.5106 - mae: 12.5106
Epoch 4/5
1/1 [==============================] - 0s 7ms/step - loss: 12.3781 - mae: 12.3781
Epoch 5/5
1/1 [==============================] - 0s 17ms/step - loss: 12.2456 - mae: 12.2456


In [11]:
X,Y

(<tf.Tensor: shape=(8, 1), dtype=float64, numpy=
 array([[-7.],
        [-4.],
        [-1.],
        [ 2.],
        [ 5.],
        [ 8.],
        [11.],
        [14.]])>,
 <tf.Tensor: shape=(8,), dtype=float64, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.])>)

In [12]:
X.ndim, Y.ndim

(2, 1)

In [13]:
model.predict([17])

1/1 [==============================] - 0s 227ms/step


array([[6.5437226]], dtype=float32)

In [14]:
# 1. Improve our model performance
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

# 2. Complile the model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
              metrics=["mae"])

# Fit the model
model.fit(X, Y, epochs=100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 13.9362 - mae: 13.9362
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 69.1165 - mae: 69.1165
Epoch 3/100
1/1 [==============================] - 0s 17ms/step - loss: 14.7650 - mae: 14.7650
Epoch 4/100
1/1 [==============================] - 0s 12ms/step - loss: 13.0948 - mae: 13.0948
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 12.5831 - mae: 12.5831
Epoch 6/100
1/1 [==============================] - 0s 10ms/step - loss: 11.5821 - mae: 11.5821
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 8.2458 - mae: 8.2458
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 8.8784 - mae: 8.8784
Epoch 9/100
1/1 [==============================] - 0s 0s/step - loss: 4.7898 - mae: 4.7898
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 7.2819 - mae: 7.2819
Epoch 11/100
1/1 [==============================] - 0s 10ms/step 

In [15]:
model.predict([1])

1/1 [==============================] - 0s 174ms/step


array([[11.041884]], dtype=float32)

In [16]:
#Create a model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

#Complile the model
model.compile(loss=tf.keras.losses.mae,
             optimizer=tf.keras.optimizers.SGD(),
             metrics=["mae"])

#Fit the model
model.fit(X,Y, epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 953ms/step - loss: 14.5626 - mae: 14.5626
Epoch 2/5
1/1 [==============================] - 0s 3ms/step - loss: 14.0461 - mae: 14.0461
Epoch 3/5
1/1 [==============================] - 0s 14ms/step - loss: 13.5341 - mae: 13.5341
Epoch 4/5
1/1 [==============================] - 0s 11ms/step - loss: 13.0220 - mae: 13.0220
Epoch 5/5
1/1 [==============================] - 0s 14ms/step - loss: 12.5253 - mae: 12.5253


In [17]:
#Create a model
model_S = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_S.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.Adam(learning_rate=0.01, beta_1=0.1, beta_2=0.1),
                metrics=["mae"])
#Fit the model
model_S.fit(X, Y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 12.3733 - mae: 12.3733
Epoch 2/100
1/1 [==============================] - 0s 9ms/step - loss: 11.5501 - mae: 11.5501
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 10.7259 - mae: 10.7259
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 9.9019 - mae: 9.9019
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 9.0706 - mae: 9.0706
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 8.4526 - mae: 8.4526
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 7.7856 - mae: 7.7856
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 7.0807 - mae: 7.0807
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 6.5059 - mae: 6.5059
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 5.6730 - mae: 5.6730
Epoch 11/100
1/1 [==============================] - 0s 16ms/step - loss

In [18]:
model_S.predict([14])

1/1 [==============================] - 0s 156ms/step


array([[26.029402]], dtype=float32)

In [19]:
x_1 = tf.constant([-2, 1, 2, 5, 6])
y_1 = tf.constant([7, 4, 9, 13, 27])
x_e = tf.reshape(x_1, shape=(5,1))
x_1, x_e, y_1

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-2,  1,  2,  5,  6])>,
 <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
 array([[-2],
        [ 1],
        [ 2],
        [ 5],
        [ 6]])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7,  4,  9, 13, 27])>)

In [20]:
#Create a model
modele = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

#Compile the model
modele.compile(loss="mae",
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.1, beta_1=0.1, beta_2=0.1),
              metrics=["mae"])

#Fit the model
modele.fit(x_e, y_1, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 12.5511 - mae: 12.5511
Epoch 2/50
1/1 [==============================] - 0s 13ms/step - loss: 8.0868 - mae: 8.0868
Epoch 3/50
1/1 [==============================] - 0s 16ms/step - loss: 3.2271 - mae: 3.2271
Epoch 4/50
1/1 [==============================] - 0s 11ms/step - loss: 3.6237 - mae: 3.6237
Epoch 5/50
1/1 [==============================] - 0s 15ms/step - loss: 3.0369 - mae: 3.0369
Epoch 6/50
1/1 [==============================] - 0s 13ms/step - loss: 3.2499 - mae: 3.2499
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 3.8178 - mae: 3.8178
Epoch 8/50
1/1 [==============================] - 0s 12ms/step - loss: 3.4820 - mae: 3.4820
Epoch 9/50
1/1 [==============================] - 0s 8ms/step - loss: 2.9190 - mae: 2.9190
Epoch 10/50
1/1 [==============================] - 0s 11ms/step - loss: 4.0363 - mae: 4.0363
Epoch 11/50
1/1 [==============================] - 0s 7ms/step - loss: 2.9996 - 

In [21]:
modele.predict([6])

1/1 [==============================] - 0s 174ms/step


array([[29.442911]], dtype=float32)

In [22]:
#Evalute a model

x_l = tf.range(-100,100, 4)
x_l = tf.reshape(x_l, shape=(50,1))

#Make labels for the dataset
y_l = x_l + 10
#Create a model
modelee = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

#Compile the model
modelee.compile(loss="mae",
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
              metrics=["mae"])

#Fit the model
modelee.fit(x_l, y_l, epochs=50)

Epoch 1/50
2/2 [==============================] - 2s 19ms/step - loss: 105.3580 - mae: 105.3580
Epoch 2/50
2/2 [==============================] - 0s 9ms/step - loss: 127.4115 - mae: 127.4115
Epoch 3/50
2/2 [==============================] - 0s 8ms/step - loss: 129.0404 - mae: 129.0404
Epoch 4/50
2/2 [==============================] - 0s 11ms/step - loss: 54.0723 - mae: 54.0723
Epoch 5/50
2/2 [==============================] - 0s 12ms/step - loss: 88.2152 - mae: 88.2152
Epoch 6/50
2/2 [==============================] - 0s 7ms/step - loss: 62.0217 - mae: 62.0217
Epoch 7/50
2/2 [==============================] - 0s 8ms/step - loss: 39.6666 - mae: 39.6666
Epoch 8/50
2/2 [==============================] - 0s 1ms/step - loss: 26.9626 - mae: 26.9626
Epoch 9/50
2/2 [==============================] - 0s 9ms/step - loss: 15.1435 - mae: 15.1435
Epoch 10/50
2/2 [==============================] - 0s 9ms/step - loss: 29.0108 - mae: 29.0108
Epoch 11/50
2/2 [==============================] - 0s 9ms/st

In [23]:
modelee.predict([-100])

1/1 [==============================] - 0s 365ms/step


array([[-73.51608]], dtype=float32)

In [37]:
# Generate test data
test_x = tf.range(1, 10, 0.1)
test_y = (test_x * tf.math.log(test_x)) ** 3 / 2
test_y = tf.reshape(test_y, shape=(test_y.shape[0], 1))

# Convert Tensorflow tensors to numpy arrays
test_x_np = test_x.numpy()
test_y_np = test_y.numpy()

# Create a model
model_test = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu", input_shape=(1,)),  # Input shape needs to be specified for single-dimensional input
    tf.keras.layers.Dense(1)
])

# Compile the model
model_test.compile(loss="mae",
                   optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
                   metrics=["mae"])

# Fit the model
model_test.fit(test_x, test_y, epochs=50)

Epoch 1/50
3/3 [==============================] - 1s 6ms/step - loss: 1208.9730 - mae: 1208.9730
Epoch 2/50
3/3 [==============================] - 0s 5ms/step - loss: 1177.7535 - mae: 1177.7535
Epoch 3/50
3/3 [==============================] - 0s 5ms/step - loss: 1130.3119 - mae: 1130.3119
Epoch 4/50
3/3 [==============================] - 0s 6ms/step - loss: 1071.8088 - mae: 1071.8088
Epoch 5/50
3/3 [==============================] - 0s 6ms/step - loss: 1016.9642 - mae: 1016.9642
Epoch 6/50
3/3 [==============================] - 0s 7ms/step - loss: 958.2508 - mae: 958.2508
Epoch 7/50
3/3 [==============================] - 0s 5ms/step - loss: 917.3544 - mae: 917.3544
Epoch 8/50
3/3 [==============================] - 0s 6ms/step - loss: 892.9915 - mae: 892.9915
Epoch 9/50
3/3 [==============================] - 0s 6ms/step - loss: 880.7950 - mae: 880.7950
Epoch 10/50
3/3 [==============================] - 0s 5ms/step - loss: 884.7868 - mae: 884.7868
Epoch 11/50
3/3 [======================

In [38]:
##The 3 sets..
#Training set - model learns from this set(70-80%)
#Validation set - we tune the model on this data(10-15%)
#Test set - Test the model what is has learned.(10-15%).
test_x[10], test_y[10], model_test.predict([2.0000002])

1/1 [==============================] - 0s 185ms/step


(<tf.Tensor: shape=(), dtype=float32, numpy=2.0000002>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.3320997], dtype=float32)>,
 array([[-3.2625732]], dtype=float32))

In [26]:
test_y.shape[0]

90

In [27]:
#!pip install --upgrade matplotlib

In [28]:
# Generate test data
test_x = tf.range(1, 10, 0.1)
test_y = (test_x * tf.math.log(test_x)) ** 3 / 2
test_y = tf.reshape(test_y, shape=(test_y.shape[0], 1))

# Convert Tensorflow tensors to numpy arrays
test_x_np = test_x.numpy()
test_y_np = test_y.numpy()

# Create a model
model_test = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu", input_shape=(1,)),  # Input shape needs to be specified for single-dimensional input
    tf.keras.layers.Dense(1)
])

# Compile the model
model_test.compile(loss="mae",
                   optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
                   metrics=["mae"])

# Fit the model
model_test.fit(test_x, test_y, epochs=10)

Epoch 1/10
3/3 [==============================] - 1s 9ms/step - loss: 1211.2544 - mae: 1211.2544
Epoch 2/10
3/3 [==============================] - 0s 7ms/step - loss: 1185.2262 - mae: 1185.2262
Epoch 3/10
3/3 [==============================] - 0s 7ms/step - loss: 1143.5078 - mae: 1143.5078
Epoch 4/10
3/3 [==============================] - 0s 8ms/step - loss: 1091.7606 - mae: 1091.7606
Epoch 5/10
3/3 [==============================] - 0s 4ms/step - loss: 1038.3433 - mae: 1038.3433
Epoch 6/10
3/3 [==============================] - 0s 10ms/step - loss: 977.7791 - mae: 977.7791
Epoch 7/10
3/3 [==============================] - 0s 6ms/step - loss: 933.9517 - mae: 933.9517
Epoch 8/10
3/3 [==============================] - 0s 6ms/step - loss: 903.1529 - mae: 903.1529
Epoch 9/10
3/3 [==============================] - 0s 6ms/step - loss: 882.9891 - mae: 882.9891
Epoch 10/10
3/3 [==============================] - 0s 7ms/step - loss: 881.8564 - mae: 881.8564


In [29]:
len(test_x)

90

In [30]:
#Split the data into test set and train set
x_train = test_x[:72]
y_train = test_y[:72]

x_test = test_x[72:]
y_test = test_y[72:]

len(x_train), len(y_train), len(x_test), len(x_test)

(72, 72, 18, 18)

In [31]:
#plt.figure(figsize=(10, 7))
#plt.scatter(x_train, y_train, c="b", label="Training data")
#plt.scatter(x_test, y_test, c="g", label="Testing data")
#plt.legend();

In [39]:
# Create a model
model_test = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, input_shape=(1,))
])

# Compile the model
model_test.compile(loss="mae",
                   optimizer=tf.keras.optimizers.SGD(),
                   metrics=["mae"])

# Fit the model
#model_test.fit(x_train, y_train, epochs=100)

In [40]:
model_test.build()
model_test.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.