In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
# Generate test data
test_x = tf.range(1, 10, 0.1)
test_y = (test_x * tf.math.log(test_x)) ** 3 / 2
test_y = tf.reshape(test_y, shape=(test_y.shape[0], 1))

In [3]:
#3 data set for machine learning models
#Split the data into test set and train set
x_train = test_x[:72]
y_train = test_y[:72]

x_test = test_x[72:]
y_test = test_y[72:]
y_train = tf.reshape(y_train, shape=(y_train.shape[0], 1))
len(x_train), len(y_train), len(x_test), len(x_test)

(72, 72, 18, 18)

In [4]:
#Create a model
tf.random.set_seed(42)
model_00 = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1]),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_00.compile(
    loss=tf.keras.losses.mae,
    optimizer =tf.keras.optimizers.SGD(),
    metrics=["mae"])

#Fit the model
model_00.fit(x_train, y_train, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 9ms/step - loss: 508.9158 - mae: 508.9158
Epoch 2/100
3/3 [==============================] - 0s 6ms/step - loss: 507.5889 - mae: 507.5889
Epoch 3/100
3/3 [==============================] - 0s 6ms/step - loss: 506.4362 - mae: 506.4362
Epoch 4/100
3/3 [==============================] - 0s 8ms/step - loss: 505.3167 - mae: 505.3167
Epoch 5/100
3/3 [==============================] - 0s 7ms/step - loss: 504.1289 - mae: 504.1289
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 502.6508 - mae: 502.6508
Epoch 7/100
3/3 [==============================] - 0s 5ms/step - loss: 501.1747 - mae: 501.1747
Epoch 8/100
3/3 [==============================] - 0s 4ms/step - loss: 499.4065 - mae: 499.4065
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 497.2703 - mae: 497.2703
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 494.6654 - mae: 494.6654
Epoch 11/100
3/3 [=====================

In [5]:
model_00.evaluate(x_train, y_train)

3/3 [==============================] - 0s 3ms/step - loss: 336.4569 - mae: 336.4569


[336.4569091796875, 336.4569091796875]

In [6]:
y_pred_1 = model_00.predict(x_test)
y_pred_1

1/1 [==============================] - 0s 205ms/step


array([[776.8049 ],
       [787.19434],
       [797.58374],
       [807.97327],
       [818.36273],
       [828.75214],
       [839.1416 ],
       [849.531  ],
       [859.92053],
       [870.30994],
       [880.6994 ],
       [891.0889 ],
       [901.4783 ],
       [911.8678 ],
       [922.2572 ],
       [932.64667],
       [943.0361 ],
       [953.4256 ]], dtype=float32)

In [7]:
y_test

<tf.Tensor: shape=(18, 1), dtype=float32, numpy=
array([[2568.2112],
       [2709.615 ],
       [2856.6938],
       [3009.591 ],
       [3168.454 ],
       [3333.4287],
       [3504.6655],
       [3682.3127],
       [3866.5217],
       [4057.4487],
       [4255.2466],
       [4460.0703],
       [4672.08  ],
       [4891.4336],
       [5118.2925],
       [5352.8184],
       [5595.1753],
       [5845.5264]], dtype=float32)>

In [8]:
#Functions for mae and mse
def mae(y_true, y_pred):
    return tf.math.reduce_mean(tf.metrics.mean_absolute_error(y_true, y_pred)).numpy()
    
def mse(y_true, y_pred):
    return tf.math.reduce_mean(tf.metrics.mean_squared_error(y_true, y_pred)).numpy()

#Plot function
def plot_preds(train_data=x_train, train_labels=y_train,
              test_data=x_test, test_labels=y_test,
              preds=y_pred_1):
    plt.figure(figsize=(10, 7))
    #Plot training in blue
    plt.scatter(train_data, train_labels, c="b",label="Training data")
    #Plot testing data in green
    plt.scatter(test_data, test_labels, c="g", label="Testing data")
    #Plot model's predictions in red
    plt.scatter(test_data, preds, c="r", label="Predictions")
    #Show legend
    plt.legend();

In [9]:
#Calculate model_1 evaluation metrics
mae_1 = mae(y_test, y_pred_1)
mse_1 = mse(y_test, y_pred_1)
mae_1, mse_1

(3187.5286, 11056370.0)

In [10]:
#Create a model
tf.random.set_seed(42)
model_01 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=[1]),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_01.compile(
    loss=tf.keras.losses.mae,
    optimizer =tf.keras.optimizers.SGD(),
    metrics=["mse"])

#Fit the model
model_01.fit(x_train, y_train, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 7ms/step - loss: 511.0794 - mse: 711747.6875
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 508.5625 - mse: 707879.6250
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 506.4001 - mse: 704330.8750
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 504.4596 - mse: 701192.8750
Epoch 5/100
3/3 [==============================] - 0s 6ms/step - loss: 502.4741 - mse: 697640.4375
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 500.0907 - mse: 693580.5625
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 497.8578 - mse: 689692.6250
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 495.1528 - mse: 684602.7500
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 491.9478 - mse: 678438.3125
Epoch 10/100
3/3 [==============================] - 0s 7ms/step - loss: 488.1207 - mse: 671292.3125
Epoch 11/

In [11]:
y_pred_2 = model_01.predict(x_test)
y_pred_2

1/1 [==============================] - 0s 110ms/step


array([[779.7463 ],
       [790.20575],
       [800.66534],
       [811.1249 ],
       [821.58435],
       [832.0438 ],
       [842.50336],
       [852.9629 ],
       [863.42236],
       [873.8819 ],
       [884.3413 ],
       [894.80084],
       [905.2604 ],
       [915.71985],
       [926.1794 ],
       [936.639  ],
       [947.0984 ],
       [957.5579 ]], dtype=float32)

In [12]:
#Calculate evaluation metrics
mae_2 = mae(y_test, y_pred_2)
mse_2 = mse(y_test, y_pred_2)
mae_2, mse_2

(3183.9917, 11033150.0)

In [13]:
#Create a model
tf.random.set_seed(42)
model_02 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=[1]),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_02.compile(
    loss=tf.keras.losses.mae,
    optimizer =tf.keras.optimizers.SGD(),
    metrics=["mse"])

#Fit the model
model_02.fit(x_train, y_train, epochs=500, verbose=0)

In [14]:
y_pred_3 =model_02.predict(x_test)
y_pred_3

1/1 [==============================] - 0s 159ms/step


array([[1115.6296],
       [1136.1938],
       [1156.7582],
       [1177.3224],
       [1197.8866],
       [1218.4509],
       [1239.0151],
       [1259.5793],
       [1280.1436],
       [1300.7078],
       [1321.272 ],
       [1341.8364],
       [1362.4005],
       [1382.9647],
       [1403.5289],
       [1424.0933],
       [1444.6575],
       [1465.2216]], dtype=float32)

In [15]:
mae_3 = mae(y_test, y_pred_3)
mse_3 = mse(y_test, y_pred_3)
mae_3, mse_3

(2762.2178, 8429101.0)

In [16]:
#Comparing the results of our experiments
#use pandas to compare our models results using pandas DataFrame
import pandas as pd

model_results = [["model_1", mae_1, mse_1],
                 ["model_2", mae_2, mse_2],
                 ["model_3", mae_3, mae_3]]
cols = ["model", "mae", "mse"]
all_results =pd.DataFrame(model_results, columns=cols)
all_results

model          mae           mse
0  model_1  3187.528564  1.105637e+07
1  model_2  3183.991699  1.103315e+07
2  model_3  2762.217773  2.762218e+03

In [17]:
tf.random.set_seed(42)
model_04 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu", input_shape=[1]),
    tf.keras.layers.Dense(10, input_shape=[1]),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_04.compile(
    loss=tf.keras.losses.mae,
    optimizer =tf.keras.optimizers.Adam(learning_rate=0.1),
    metrics=["mse"])

#Fit the model
model_04.fit(x_train, y_train, epochs=100)


Epoch 1/100
3/3 [==============================] - 1s 8ms/step - loss: 503.8300 - mse: 699867.1250
Epoch 2/100
3/3 [==============================] - 0s 7ms/step - loss: 486.1287 - mse: 666573.2500
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 449.8206 - mse: 578657.4375
Epoch 4/100
3/3 [==============================] - 0s 6ms/step - loss: 407.9526 - mse: 448799.3125
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 373.7609 - mse: 290434.8750
Epoch 6/100
3/3 [==============================] - 0s 9ms/step - loss: 389.5590 - mse: 239761.1094
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 398.7212 - mse: 223547.1875
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 376.7838 - mse: 227406.4688
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 364.4771 - mse: 272562.9375
Epoch 10/100
3/3 [==============================] - 0s 786us/step - loss: 356.0619 - mse: 305462.1562
Epoch 1

In [18]:
y_pred_4 = model_04.predict(x_test)
y_pred_4

1/1 [==============================] - 0s 125ms/step


array([[2298.758 ],
       [2388.5803],
       [2478.403 ],
       [2568.225 ],
       [2658.0476],
       [2747.8699],
       [2837.6921],
       [2927.5144],
       [3017.3372],
       [3107.1592],
       [3196.9817],
       [3286.8035],
       [3376.626 ],
       [3466.4485],
       [3556.2708],
       [3646.093 ],
       [3735.9153],
       [3825.738 ]], dtype=float32)

In [19]:
mae_4 = mae(y_test, y_pred_4)
mse_4 = mse(y_test, y_pred_4)
mae_4, mse_4

(990.3956, 1269454.9)

In [20]:
tf.random.set_seed(42)
model_05 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu", input_shape=[1]),
    tf.keras.layers.Dense(10, activation="relu", input_shape=[1]),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_05.compile(
    loss=tf.keras.losses.mae,
    optimizer =tf.keras.optimizers.Adam(learning_rate=0.1),
    metrics=["mse"])

#Fit the model
model_05.fit(x_train, y_train, epochs=100)


Epoch 1/100
3/3 [==============================] - 1s 12ms/step - loss: 502.7859 - mse: 697958.7500
Epoch 2/100
3/3 [==============================] - 0s 7ms/step - loss: 482.5347 - mse: 658918.9375
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 438.0825 - mse: 549824.3125
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 394.7027 - mse: 400297.8438
Epoch 5/100
3/3 [==============================] - 0s 8ms/step - loss: 374.4867 - mse: 250853.3125
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 402.1786 - mse: 227847.6875
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 394.7226 - mse: 221169.3906
Epoch 8/100
3/3 [==============================] - 0s 6ms/step - loss: 367.5192 - mse: 245979.2188
Epoch 9/100
3/3 [==============================] - 0s 8ms/step - loss: 366.6139 - mse: 315493.0625
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 366.3052 - mse: 354546.0312
Epoch 11

In [21]:
y_pred_5 = model_05.predict(x_test)
y_pred_5

1/1 [==============================] - 0s 134ms/step


array([[2329.5361],
       [2416.9607],
       [2504.3853],
       [2591.8096],
       [2679.2344],
       [2766.659 ],
       [2854.0837],
       [2941.508 ],
       [3028.9326],
       [3116.357 ],
       [3203.7815],
       [3291.206 ],
       [3378.6309],
       [3466.0552],
       [3553.4797],
       [3640.9043],
       [3728.3286],
       [3815.7532]], dtype=float32)

In [22]:
mae_5 = mae(y_test, y_pred_5)
mse_5 = mse(y_test, y_pred_5)
mae_5, mse_5

(979.9989, 1262334.4)

In [23]:
tf.random.set_seed(42)
model_06 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu", input_shape=[1]),
    tf.keras.layers.Dense(1)
])

#Compile a model
model_06.compile(
    loss=tf.keras.losses.mae,
    optimizer =tf.keras.optimizers.Adam(learning_rate=0.1),
    metrics=["mse"])

#Fit the model
model_06.fit(x_train, y_train, epochs=100, verbose=0)

In [28]:
y_pred_6 =model_06.predict(x_test)
y_pred_6
mae_6 = mae(y_test, y_pred_6)
mse_6 = mse(y_test, y_pred_6)
mae_6, mse_6

1/1 [==============================] - 0s 53ms/step


(2641.1243, 7746754.0)

In [29]:


model_results_2 = [["model 4", mae_4, mse_4],
                   ["model 5",mae_5, mse_5],
                   ["model 6",mae_6, mse_6]]
cols = ["Models", "MAE", "MSE"]
all_results_2 = pd.DataFrame(model_results_2, columns=cols)
all_results_2

Models          MAE          MSE
0  model 4   990.395630  1269454.875
1  model 5   979.998901  1262334.375
2  model 6  2641.124268  7746754.000

In [30]:
#Save models format
#1. savedMode format
#2. HDF5 format
model_04.save("best_model_04")

INFO:tensorflow:Assets written to: best_model_04\assets


In [31]:
model_04.save("my_best_model.h5")

In [32]:
#Load saved models
new_model = tf.keras.models.load_model("best_model_04")
new_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                20        
                                                                 
 dense_7 (Dense)             (None, 10)                110       
                                                                 
 dense_8 (Dense)             (None, 1)                 11        
                                                                 
Total params: 141
Trainable params: 141
Non-trainable params: 0
_________________________________________________________________


In [33]:
model_04.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                20        
                                                                 
 dense_7 (Dense)             (None, 10)                110       
                                                                 
 dense_8 (Dense)             (None, 1)                 11        
                                                                 
Total params: 141
Trainable params: 141
Non-trainable params: 0
_________________________________________________________________


In [35]:
y_pred_new = new_model.predict(x_test)
y_pred_new == y_pred_4

1/1 [==============================] - 0s 65ms/step


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [37]:
new_model_2 = tf.keras.models.load_model("my_best_model.h5")
new_model_2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                20        
                                                                 
 dense_7 (Dense)             (None, 10)                110       
                                                                 
 dense_8 (Dense)             (None, 1)                 11        
                                                                 
Total params: 141
Trainable params: 141
Non-trainable params: 0
_________________________________________________________________
